// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpjkyqememcdhclbsrif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwamt5cWVtZW1jZGhjbGJzcmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjE5MDQsImV4cCI6MjA3MzE5NzkwNH0.ZaaIJZ239naLCqLaH6YUBXIHW4F7lGawGqLamDiw5aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});